# Generated by Django 3.2.8 on 2021-11-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='dolphin',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
